import random

FACTS = [
    "A day on Venus is longer than a year on Venus.",
    "Neutron stars can spin 600 times per second.",
    "Jupiter protects Earth by absorbing many comets.",
    "The Moon is moving away from Earth by 3.8 cm per year.",
    "There are more trees on Earth than stars in the Milky Way.",
    "Saturn could float in water due to its low density.",
    "One million Earths could fit inside the Sun.",
    "The footprints on the Moon will last millions of years.",
    "Olympus Mons on Mars is the tallest volcano in the solar system.",
    "A teaspoon of neutron star weighs about a billion tons.",
    "Mercury has no atmosphere to trap heat, so it has extreme temperature changes.",
    "Uranus rotates on its side.",
    "Mars has the largest dust storms in the Solar System.",
    "Jupiter has a giant storm called the Great Red Spot.",
    "Saturn has the most visible ring system.",
    "Neptune has the fastest winds in the Solar System.",
    "Pluto is smaller than Earth’s Moon.",
    "Halley's Comet appears every 76 years.",
    "Light from the Sun takes about 8 minutes to reach Earth.",
    "Earth is the only known planet with life.",
    "The Milky Way galaxy has billions of stars.",
    "A black hole has gravity so strong that even light cannot escape.",
    "Ganymede is the largest moon in the Solar System.",
    "Europa may have an ocean under its ice.",
    "Titan has lakes of liquid methane.",
    "Ceres is the largest object in the asteroid belt.",
    "Betelgeuse is much bigger than the Sun.",
    "Andromeda Galaxy is moving toward the Milky Way.",
    "Venus is the hottest planet in our Solar System.",
    "The International Space Station travels around Earth every 90 minutes.",
    "A year on Mercury is only 88 Earth days.",
    "Neptune was discovered using mathematics.",
    "Mars has two small moons called Phobos and Deimos.",
    "Jupiter has more than 90 known moons.",
    "The Moon has moonquakes.",
    "Saturn has a hexagon-shaped storm at its north pole.",
    "Uranus is the coldest planet.",
    "The Kuiper Belt is full of icy objects.",
    "A supernova is a powerful star explosion.",
    "The Hubble Space Telescope has taken thousands of space images.",
    "Proxima Centauri is the closest star to the Sun.",
    "The Oort Cloud surrounds our Solar System.",
    "Valles Marineris is the largest canyon in the Solar System.",
    "Kepler-452b is sometimes called Earth’s cousin.",
    "Alpha Centauri is the closest star system to us.",
    "The Sun is about 4.6 billion years old.",
    "Enceladus shoots water into space.",
    "Callisto has many craters.",
    "The Asteroid Belt lies between Mars and Jupiter.",
    "Neutron stars are formed after a supernova.",
    "Mars looks red because of iron oxide (rust).",
    "Venus rotates in the opposite direction of most planets.",
    "The Moon is about 4.5 billion years old.",
    "Jupiter has the shortest day of all planets.",
    "Neptune takes about 165 Earth years to orbit the Sun.",
    "The Sun is a medium-sized star.",
    "Earth has one natural satellite.",
    "Io is the most volcanic moon.",
    "The Milky Way will collide with Andromeda in the future.",
    "Mars sunsets appear blue.",
    "Mercury has ice at its poles.",
    "Venus has thick clouds of sulfuric acid.",
    "Earth is about 4.5 billion years old.",
    "Mars has frozen water at its poles.",
    "Jupiter has the strongest magnetic field of any planet.",
    "Saturn has over 140 known moons.",
    "Uranus has faint rings.",
    "Neptune was first seen in 1846.",
    "Pluto has five known moons.",
    "The Moon causes ocean tides on Earth.",
    "The Sun produces energy by nuclear fusion.",
    "The Milky Way is a spiral galaxy.",
    "The Andromeda Galaxy is larger than the Milky Way.",
    "Ganymede has its own magnetic field.",
    "Europa has cracks in its icy surface.",
    "Titan has a thick orange atmosphere.",
    "Io has hundreds of volcanoes.",
    "Callisto is one of the oldest surfaces in the Solar System.",
    "Enceladus has icy geysers.",
    "Ceres may have salty water underground.",
    "A black hole can bend light.",
    "A supernova can outshine a whole galaxy.",
    "Betelgeuse may explode someday.",
    "Proxima Centauri has at least one planet.",
    "Alpha Centauri is about 4.3 light-years away.",
    "The International Space Station orbits about 400 km above Earth.",
    "The Hubble Space Telescope was launched in 1990.",
    "The James Webb Space Telescope studies infrared light.",
    "Valles Marineris is over 4,000 km long.",
    "The Kuiper Belt lies beyond Neptune.",
    "The Oort Cloud may contain billions of comets.",
    "Halley's Comet was last seen in 1986.",
    "Kepler-452b orbits a Sun-like star.",
    "Sagittarius A* is at the center of the Milky Way.",
    "Neutron stars are extremely hot when formed.",
    "Mercury has the shortest year of all planets.",
    "Venus has no moons.",
    "Earth is slightly flattened at the poles.",
    "Mars has the largest volcano in the Solar System.",
    "Jupiter spins very fast.",
    "Saturn is less dense than water.",
    "Uranus appears blue-green.",
    "Neptune is very cold and dark.",
    "Pluto has a heart-shaped region.",
    "The Moon always shows the same side to Earth.",
    "The Sun will become a red giant one day.",
    "The Milky Way contains dark matter.",
    "A pulsar sends regular radio pulses.",
    "Ganymede is bigger than Mercury.",
    "Titan has rain made of methane.",
    "Some stars are bigger than our Sun.",
    "Some stars are smaller than Earth.",
    "Space is completely silent.",
    "Light travels faster than anything else.",
    "One light-year is about 9.46 trillion km.",
    "Galaxies come in spiral, elliptical, and irregular shapes.",
    "There are billions of galaxies in the universe.",
    "Astronauts grow taller in space.",
    "Space has no air to breathe.",
    "Rockets need huge fuel to escape gravity.",
    "Meteors glow when entering Earth’s atmosphere.",
    "Asteroids are rocky space objects.",
    "Comets have tails when near the Sun.",
    "The universe is about 13.8 billion years old.",
    "Gravity keeps planets in orbit.",
    "The North Star helps in navigation.",
    "Solar eclipses happen when the Moon blocks the Sun.",
    "Lunar eclipses happen when Earth blocks sunlight to the Moon.",
    "The Solar System formed from gas and dust.",
    "Mars has seasons like Earth.",
    "Venus is sometimes called Earth’s twin.",
    "Jupiter acts like a giant shield.",
    "Saturn’s rings are made of ice and rock.",
    "Uranus takes 84 Earth years to orbit the Sun.",
    "Neptune was predicted before being seen.",
    "Pluto was reclassified as a dwarf planet in 2006.",
    "The Moon has no atmosphere.",
    "The Sun’s surface is about 5,500°C.",
    "Shooting stars are not real stars.",
    "A galaxy can contain billions of planets.",
    "Some planets are made mostly of gas.",
    "Earth’s atmosphere protects us from meteors.",
    "The Sun is about 150 million km from Earth.",
    "Stars twinkle because of Earth’s atmosphere.",
    "Mars has the longest valley in the Solar System.",
    "Spacecraft have visited every planet.",
    "The ISS is visible from Earth at night.",
    "The first human in space was Yuri Gagarin.",
    "The first Moon landing was in 1969.",
    "Black holes form from dying massive stars.",
    "Some stars live for billions of years.",
    "The largest known stars are called supergiants.",
    "Earth rotates once every 24 hours.",
    "Planets orbit the Sun in elliptical paths.",
    "The Sun is a yellow dwarf star.",
    "Our galaxy will change shape after collision.",
    "Some moons may have life-friendly conditions.",
    "Space probes send data back to Earth.",
    "Astronauts train for years before missions.",
    "The universe is still expanding.",
    "The Sun contains about 73% hydrogen.",
    "The Sun contains about 25% helium.",
    "Solar flares can affect satellites.",
    "Coronal mass ejections can disturb Earth’s magnetic field.",
    "The Sun’s core is about 15 million °C.",
    "The Sun rotates once about every 27 days.",
    "Sunspots are cooler areas on the Sun.",
    "The solar wind flows constantly from the Sun.",
    "Earth’s magnetic field protects us from solar wind.",
    "The aurora is caused by charged solar particles.",
    "The asteroid Vesta is one of the largest asteroids.",
    "Some asteroids have small moons.",
    "Trojan asteroids share Jupiter’s orbit.",
    "Meteoroids are smaller than asteroids.",
    "Micrometeorites fall to Earth every day.",
    "A fireball is a very bright meteor.",
    "Meteor showers happen yearly.",
    "The Perseid meteor shower peaks in August.",
    "The Leonid meteor shower peaks in November.",
    "Some comets take thousands of years to orbit the Sun.",
    "Long-period comets come from far regions of space.",
    "Short-period comets orbit in less than 200 years.",
    "Comet tails always point away from the Sun.",
    "There are rogue planets without stars.",
    "Brown dwarfs are between planets and stars.",
    "Red dwarfs are the most common stars.",
    "Blue stars are hotter than yellow stars.",
    "White dwarfs are very dense.",
    "The closest galaxy to us is the Canis Major Dwarf Galaxy.",
    "Galaxy clusters contain hundreds of galaxies.",
    "Dark energy causes the universe to expand faster.",
    "Gravity is the weakest fundamental force.",
    "The first exoplanet was discovered in 1992.",
    "Thousands of exoplanets are now known.",
    "Some exoplanets orbit two stars.",
    "Some planets rain glass sideways.",
    "The hottest known planets are called hot Jupiters.",
    "Super-Earths are bigger than Earth but smaller than Neptune.",
    "Mini-Neptunes are smaller gas giants.",
    "Some exoplanets are completely covered in lava.",
    "The Sun will live about 5 billion more years.",
    "When stars die, they create heavy elements.",
    "Gold was formed in star explosions.",
    "Carbon in our bodies came from stars.",
    "Without gravity, planets would drift away.",
    "The Solar System moves around the galaxy.",
    "It takes about 225 million years to orbit the galaxy.",
    "This journey is called a galactic year.",
    "The center of Earth is extremely hot.",
    "Earth’s atmosphere has five main layers.",
    "The stratosphere contains the ozone layer.",
    "The thermosphere is where auroras happen.",
    "The exosphere is the outermost layer.",
    "Mars has a thin carbon dioxide atmosphere.",
    "Venus has a runaway greenhouse effect.",
    "Mercury has no weather.",
    "Jupiter emits more heat than it receives.",
    "Saturn also gives off extra heat.",
    "Uranus has the coldest atmospheric temperatures.",
    "Neptune’s blue color comes from methane gas.",
    "The Moon has water molecules in its soil.",
    "The Moon’s gravity is one-sixth of Earth’s.",
    "Footprints on the Moon stay for long periods.",
    "The far side of the Moon is not always dark.",
    "Mars once had flowing water.",
    "Mars has polar ice caps.",
    "Jupiter’s moon Europa may support life.",
    "Saturn’s moon Enceladus may have a warm ocean.",
    "Titan has organic molecules.",
    "Ganymede has underground oceans.",
    "Some stars explode as hypernovae.",
    "Gamma-ray bursts are the most powerful explosions.",
    "Quasars are extremely bright galactic centers.",
    "The observable universe is about 93 billion light-years wide.",
    "Space between galaxies is not completely empty.",
    "Cosmic rays constantly hit Earth.",
    "The Sun’s gravity holds the Solar System together.",
    "Earth’s axis tilt causes seasons.",
    "Mars also has axial tilt.",
    "Venus has almost no tilt.",
    "Jupiter’s magnetic field is huge.",
    "Saturn’s rings are very thin.",
    "Uranus has 27 known moons.",
    "Neptune has a moon named Triton.",
    "Triton orbits Neptune backward.",
    "Pluto’s largest moon is Charon.",
    "Pluto and Charon are tidally locked.",
    "Some dwarf planets are beyond Pluto.",
    "Space probes use gravity assists.",
    "Voyager 1 is now in interstellar space.",
    "Voyager 2 visited Uranus and Neptune.",
    "The speed of light is about 300,000 km per second.",
    "Space has a temperature close to absolute zero.",
    "Sound cannot travel in space.",
    "Astronauts wear suits to survive vacuum.",
    "The Milky Way smells like burnt toast (scientists detected chemicals).",
    "Some galaxies are billions of years old.",
    "The first artificial satellite was Sputnik 1.",
    "Earth’s rotation is slowly slowing down.",
    "The universe may continue expanding forever.",
    "The Sun’s core rotates faster than its surface.",
    "Mercury has a weak magnetic field despite its small size.",
    "Venus’s retrograde rotation may be caused by a giant impact.",
    "Mars has ice buried beneath its surface near the equator.",
    "Jupiter’s magnetic tail extends past Saturn’s orbit.",
    "Saturn’s ring particles range from micrometers to meters in size.",
    "Uranus emits less energy than it receives from the Sun.",
    "Neptune was the first planet found by mathematical prediction.",
    "Pluto has mountain ranges made of water ice.",
    "The Moon’s regolith contains tiny glass beads from micrometeorite impacts.",
    "Mercury experiences solar tides due to its elliptical orbit.",
    "Venus has sulfuric acid clouds that rain but evaporate before hitting the ground.",
    "Mars has auroras near its poles despite no global magnetic field.",
    "Jupiter radiates almost twice as much heat as it receives from the Sun.",
    "Saturn’s moon Titan has seasonal methane rainstorms.",
    "Uranus has a faint magnetosphere tilted relative to its rotation axis.",
    "Neptune’s atmosphere has bright methane clouds that move rapidly.",
    "Pluto rotates once every 6.4 Earth days.",
    "The Moon’s far side has more craters than the near side.",
    "Mercury’s surface has huge scarps formed by cooling and contraction.",
    "Venus’s surface has pancake-like volcanic domes.",
    "Mars has massive canyons like Valles Marineris.",
    "Jupiter’s moon Ganymede is larger than the planet Mercury.",
    "Saturn’s moon Iapetus has a contrasting dark and bright hemisphere.",
    "Uranus’s north pole is tipped toward the Sun for decades.",
    "Neptune’s moon Triton has nitrogen geysers.",
    "Pluto has thin nitrogen and methane ice plains.",
    "The Moon’s crust is thicker on the far side.",
    "Mercury has water ice in permanently shadowed craters near the poles.",
    "Venus has lightning in its dense atmosphere.",
    "Mars has recurring seasonal slope streaks possibly from briny water.",
    "Jupiter has faint rings made of dust particles.",
    "Saturn’s rings cast shadows across the planet.",
    "Uranus has 13 known faint rings.",
    "Neptune’s rings contain arcs that remain stable over decades.",
    "Pluto has a thin atmosphere that expands when closer to the Sun.",
    "The Moon’s mascons affect spacecraft orbits.",
    "Mercury’s exosphere is composed of sodium, potassium, and oxygen atoms.",
    "Venus rotates very slowly, taking 243 Earth days per rotation.",
    "Mars has volcanoes taller than Mount Everest.",
    "Jupiter has a thin ring system discovered in 1979.",
    "Saturn’s moon Enceladus has water ice plumes that feed its E-ring.",
    "Uranus’s largest moons are named after Shakespearean characters.",
    "Neptune has supersonic winds over 2,000 km/h.",
    "Pluto’s moon Charon is tidally locked to Pluto.",
    "The Moon always shows the same side to Earth.",
    "Mercury’s dayside temperatures can reach 430°C.",
    "Venus’s atmospheric pressure is 90 times Earth’s.",
    "Mars has polar caps that grow and shrink with seasons.",
    "Jupiter’s Great Red Spot is shrinking slowly over decades.",
    "Saturn’s moon Mimas resembles the Death Star from Star Wars.",
    "Uranus was the first planet discovered in the modern era.",
    "Neptune’s discovery confirmed Newtonian gravitational predictions.",
    "Pluto’s orbit is highly inclined compared to planets.",
    "The Moon has small quakes caused by tidal forces.",
    "Mercury’s orbit precesses due to general relativity.",
    "Venus may have active volcanoes reshaping its surface.",
    "Mars has dust storms that can cover the entire planet.",
    "Jupiter’s core may be partially dissolved.",
    "Saturn has more than 80 moons.",
    "Uranus emits faint infrared radiation.",
    "Neptune’s magnetic field is tilted relative to its rotation axis.",
    "Pluto has a heart-shaped region called Tombaugh Regio.",
    "The Moon formed about 4.5 billion years ago after a giant impact.",
    "Mercury’s density is second highest after Earth.",
    "Venus’s clouds move faster than its surface rotates.",
    "Mars’s thin atmosphere is mostly carbon dioxide.",
    "Jupiter’s radiation belts are much stronger than Earth’s Van Allen belts.",
    "Saturn’s rings may have formed from a destroyed moon.",
    "Uranus’s atmosphere contains methane giving it a blue-green color.",
    "Neptune’s moon Proteus is irregularly shaped.",
    "Pluto has five known moons.",
    "The Moon’s gravity is one-sixth of Earth’s.",
    "Mercury has no natural satellites.",
    "Venus has no moons.",
    "Mars has two tiny moons named Phobos and Deimos.",
    "Jupiter has over 90 moons.",
    "Saturn’s largest moon, Titan, has a thick atmosphere.",
    "Uranus’s moons may have subsurface oceans.",
    "Neptune’s moon Triton orbits backward, likely captured.",
    "Pluto’s moon Nix has an irregular shape.",
    "The Moon’s surface is covered by fine dust called regolith.",
    "Mercury has long cliffs called lobate scarps.",
    "Venus may have pancake-shaped lava domes.",
    "Mars has massive volcanoes like Olympus Mons.",
    "Jupiter emits more heat than it receives from the Sun.",
    "Saturn’s polar hexagon is a persistent storm.",
    "Uranus rotates almost on its side.",
    "Neptune was predicted mathematically before being observed.",
    "Pluto was classified as a dwarf planet in 2006.",
    "The Moon has permanently shadowed craters with ice.",
    "Mercury’s surface resembles the Moon’s in appearance.",
    "Venus has a runaway greenhouse effect.",
    "Mars has seasons like Earth.",
    "Jupiter’s spin makes it an oblate spheroid.",
    "Saturn’s density is less than water.",
    "Uranus’s magnetic field is offset from its center.",
    "Neptune has the fastest winds in the Solar System.",
    "Pluto’s orbit is highly eccentric."
    "Mercury has a weak magnetic field despite its small size.",
    "Venus’s retrograde rotation may be caused by a giant impact.",
    "Mars has ice buried beneath its surface near the equator.",
    "Jupiter’s magnetic tail extends past Saturn’s orbit.",
    "Saturn’s ring particles range from micrometers to meters in size.",
    "Uranus emits less energy than it receives from the Sun.",
    "Neptune was the first planet found by mathematical prediction.",
    "Pluto has mountain ranges made of water ice.",
    "The Moon’s regolith contains tiny glass beads from micrometeorite impacts.",
    "Mercury experiences solar tides due to its elliptical orbit.",
    "Venus has lightning in its dense atmosphere.",
    "Mars has auroras near its poles despite no global magnetic field.",
    "Jupiter radiates almost twice as much heat as it receives from the Sun.",
    "Saturn’s moon Titan has seasonal methane rainstorms.",
    "Uranus has a faint magnetosphere tilted relative to its rotation axis.",
    "Neptune’s atmosphere has bright methane clouds that move rapidly.",
    "Pluto rotates once every 6.4 Earth days.",
    "The Moon’s far side has more craters than the near side.",
    "Mercury’s surface has huge scarps formed by cooling and contraction.",
    "Venus’s surface has pancake-like volcanic domes.",
    "Mars has massive canyons like Valles Marineris.",
    "Jupiter’s moon Ganymede is larger than the planet Mercury.",
    "Saturn’s moon Iapetus has a contrasting dark and bright hemisphere.",
    "Uranus’s north pole is tipped toward the Sun for decades.",
    "Neptune’s moon Triton has nitrogen geysers.",
    "Pluto has thin nitrogen and methane ice plains.",
    "The Moon’s crust is thicker on the far side.",
    "Mercury has water ice in permanently shadowed craters near the poles.",
    "Venus has lightning storms in its clouds.",
    "Mars has recurring slope streaks possibly from briny water.",
    "Jupiter has faint rings made of dust particles.",
    "Saturn’s rings cast shadows across the planet.",
    "Uranus has 13 known faint rings.",
    "Neptune’s rings contain arcs that remain stable over decades.",
    "Pluto has a thin atmosphere that expands when closer to the Sun.",
    "The Moon’s mascons affect spacecraft orbits.",
    "Mercury’s exosphere is composed of sodium, potassium, and oxygen atoms.",
    "Venus rotates very slowly, taking 243 Earth days per rotation.",
    "Mars has volcanoes taller than Mount Everest.",
    "Jupiter has a thin ring system discovered in 1979.",
    "Saturn’s moon Enceladus has water ice plumes that feed its E-ring.",
    "Uranus’s largest moons are named after Shakespearean characters.",
    "Neptune has supersonic winds over 2,000 km/h.",
    "Pluto’s moon Charon is tidally locked to Pluto.",
    "The Moon always shows the same side to Earth.",
    "Mercury’s dayside temperatures can reach 430°C.",
    "Venus’s atmospheric pressure is 90 times Earth’s.",
    "Mars has polar caps that grow and shrink with seasons.",
    "Jupiter’s Great Red Spot is shrinking slowly over decades.",
    "Saturn’s moon Mimas resembles the Death Star from Star Wars.",
    "Uranus was the first planet discovered in the modern era.",
    "Neptune’s discovery confirmed Newtonian gravitational predictions.",
    "Pluto’s orbit is highly inclined compared to planets.",
    "The Moon has small quakes caused by tidal forces.",
    "Mercury’s orbit precesses due to general relativity.",
    "Venus may have active volcanoes reshaping its surface.",
    "Mars has dust storms that can cover the entire planet.",
    "Jupiter’s core may be partially dissolved.",
    "Saturn has more than 80 moons.",
    "Uranus emits faint infrared radiation.",
    "Neptune’s magnetic field is tilted relative to its rotation axis.",
    "Pluto has a heart-shaped region called Tombaugh Regio.",
    "The Moon formed about 4.5 billion years ago after a giant impact.",
    "Mercury’s density is second highest after Earth.",
    "Venus’s clouds move faster than its surface rotates.",
    "Mars’s thin atmosphere is mostly carbon dioxide.",
    "Jupiter’s radiation belts are much stronger than Earth’s Van Allen belts.",
    "Saturn’s rings may have formed from a destroyed moon.",
    "Uranus’s atmosphere contains methane giving it a blue-green color.",
    "Neptune’s moon Proteus is irregularly shaped.",
    "Pluto has five known moons.",
    "The Moon’s gravity is one-sixth of Earth’s.",
    "Mercury has no natural satellites.",
    "Venus has no moons.",
    "Mars has two tiny moons named Phobos and Deimos.",
    "Jupiter has over 90 moons.",
    "Saturn’s largest moon, Titan, has a thick atmosphere.",
    "Uranus’s moons may have subsurface oceans.",
    "Neptune’s moon Triton orbits backward, likely captured.",
    "Pluto’s moon Nix has an irregular shape.",
    "The Moon’s surface is covered by fine dust called regolith.",
    "Mercury has long cliffs called lobate scarps.",
    "Venus may have pancake-shaped lava domes.",
    "Mars has massive volcanoes like Olympus Mons.",
    "Jupiter emits more heat than it receives from the Sun.",
    "Saturn’s polar hexagon is a persistent storm.",
    "Uranus rotates almost on its side.",
    "Neptune was predicted mathematically before being observed.",
    "Pluto was classified as a dwarf planet in 2006.",
    "The Moon has permanently shadowed craters with ice.",
    "Mercury’s surface resembles the Moon’s in appearance.",
    "Venus has a runaway greenhouse effect.",
    "Mars has seasons like Earth.",
    "Jupiter’s spin makes it an oblate spheroid.",
    "Saturn’s density is less than water.",
    "Uranus’s magnetic field is offset from its center.",
    "Neptune has the fastest winds in the Solar System.",
    "Pluto’s orbit is highly eccentric.",
]

last_fact = None


def get_random_fact():
    global last_fact

    fact = random.choice(FACTS)

    while fact == last_fact:
        fact = random.choice(FACTS)

    last_fact = fact
    return fact
